#!/usr/bin/env sh

echo "🔄 Running post-checkout tasks..."

# Optional: Run turbo prune when branch changes
echo "   - Pruning Turbo cache for web apps"
pnpm turbo prune --scope=web

# Optional: Automatic dependency installation
echo "   - Installing dependencies"
pnpm install

echo "✅ post-checkout done."
